from fastapi import APIRouter
from fastapi import Depends
from fastapi import status
from fastapi import Body
from fastapi.security import OAuth2PasswordRequestForm
from app.v1.schema import ingresos_schema
from app.v1.service import Tablaingresos_services
from app.v1.service import Tablaingresos_services
from app.v1.schema.ingresos_schema import Ingresos_Schema
from app.v1.utils.db import get_db